version: "3.8"

services:
  database:
    image: postgres:17
    container_name: fynkapp_database_container
    restart: always
    env_file:
      - .env 
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data  

  backend:
    build: ./server
    container_name: fynkapp_backend_container
    restart: always  
    ports:
      - "5000:5000"
    env_file:
      - .env  
    depends_on:
      database:
        condition: service_healthy

volumes:
  pgdata:
